APP_PORT: 8080
APP_HOST: "localhost"

PG_DATABASE_HOST: "localhost"
PG_DATABASE_PORT: "5432"
PG_DATABASE_USER_ID: "postgres"
PG_DATABASE_PASSWORD: ""
PG_DB_NAME: "merge"

JWT_EXPIRY: 100
JWT_SECRET: "secret"