// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/megre/dto"

	merrors "github.com/megre/merrors"

	mock "github.com/stretchr/testify/mock"
)

// ItemService is an autogenerated mock type for the ItemService type
type ItemService struct {
	mock.Mock
}

// AddItem provides a mock function with given fields: ctx, itemRequest
func (_m *ItemService) AddItem(ctx context.Context, itemRequest dto.ItemRequest) (dto.ItemResponse, *merrors.Error) {
	ret := _m.Called(ctx, itemRequest)

	var r0 dto.ItemResponse
	if rf, ok := ret.Get(0).(func(context.Context, dto.ItemRequest) dto.ItemResponse); ok {
		r0 = rf(ctx, itemRequest)
	} else {
		r0 = ret.Get(0).(dto.ItemResponse)
	}

	var r1 *merrors.Error
	if rf, ok := ret.Get(1).(func(context.Context, dto.ItemRequest) *merrors.Error); ok {
		r1 = rf(ctx, itemRequest)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*merrors.Error)
		}
	}

	return r0, r1
}

// GetItem provides a mock function with given fields: ctx, itemID
func (_m *ItemService) GetItem(ctx context.Context, itemID string) (dto.ItemResponse, *merrors.Error) {
	ret := _m.Called(ctx, itemID)

	var r0 dto.ItemResponse
	if rf, ok := ret.Get(0).(func(context.Context, string) dto.ItemResponse); ok {
		r0 = rf(ctx, itemID)
	} else {
		r0 = ret.Get(0).(dto.ItemResponse)
	}

	var r1 *merrors.Error
	if rf, ok := ret.Get(1).(func(context.Context, string) *merrors.Error); ok {
		r1 = rf(ctx, itemID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*merrors.Error)
		}
	}

	return r0, r1
}

type mockConstructorTestingTNewItemService interface {
	mock.TestingT
	Cleanup(func())
}

// NewItemService creates a new instance of ItemService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewItemService(t mockConstructorTestingTNewItemService) *ItemService {
	mock := &ItemService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
